language: ruby
branches:
  only:
    - master
before_install:
  - echo $key_secret_password | gpg --passphrase-fd 0 deploy_key.gpg
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - ssh-add -l
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"
jobs:
  include:
    - stage: cron
      if: type = cron
      script:
        - ruby ./generate.rb
        - bash ./deploy.sh
env:
  global:
    secure: "szkTeTOxNXMOhj+6qlfWLzNQUL83wqZ7NTc4lGSBh2kaZLSitndZ3UtnVm/dsbAX/xXsoV6vCUpx2Vb9Ad+NyV+WE59amM0QfI3HAydot+ihaTokQnh4Z9BnOGDPph+QvdjI27b2mMZFQ/8lbuzoBNYkq6Om56T6Sol/xgX8OMv5kafuMqy/VIz7f1dfdNTWNtVhIsBJoa8h4d/Noxjjug+cuBLOals/z4iqP2kVjp1IqhOey0NNWTKN680Qe8uNCOqy8xlhwtLqhWT6D0FWUkyHfpspdjyvRYqsoaO2rLbYCzj6JPnvN77Xru5hGxC+mPuIW9zPQcBYxMWDEpoZyeqTbTkmlcIttfVTyjk6S4QY707a23fINnySC3xZ/xwSpLFJ7/ykmnTh3w7V2XoFj5gOVccyzepnXqrB+TqnqeK6+R1PvPjR5hHj5ml7yBjmfqTggQqNlTXpsAe+IOe+IHztQuWIydkD5n+V1gPFusRggcx10h1k689kSjJBhjNiieHbK1bDmTj+SXQ/twiChRMOBc5O7nRiJ3Oe/WoVghseJlVm1t2NY2ZocDVWKR90bOrB5JHxZVlXVjVgGKlm39t/nmGDgg1d+I5hr6wQjkgGh98jIuTFOZ4cSH/Cgq27VTP7xPtLsfW9XwdRTCQxcLGE6McGjmc+RpImHK1+rwA="

