language: ruby
branches:
  only:
    - master
before_install:
  - echo $key_secret_password | gpg --passphrase-fd 0 deploy_key.gpg
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - ssh-add -l
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"
jobs:
  include:
    - stage: cron
      if: type = cron
      script:
        - ruby ./generate.rb
        - bash ./deploy.sh
env:
  global:
    secure: "iC/NmOInhWpSH2B/PhQaOnJ/H0tnq53uL6HwM3m4MlSs3XPt4nl4qvozhKRIjeotJkHEKVb4U1UHeZ370Fmj9ZRtV8pk2aqy72wDfcmoUjgLWTH4ujL7W8sGdvbmjl/bBPilE6pAZ0KIc7VM+e09YMx1R+Q9PNJEWjp/wtfRiZ/VlZtrF8z8M0/ZEhrSb03hB1Z8bRIiXF19ADoLjDLQDbIFP3KSHx1rdBw7tLJBqoNdjRyJYDOH//ZGomZIMmLhd+VvZscS+YMwHIsPxhX9xYUvzB6s/I/mzpYaq+Y1ubjvkrB4/oMBE03R2sh+KL21n/3f5falKJiXgHlEHj2VF3ztNPkYsQ0J55DRGHnIY6qJbsTLmRY+K/B2sptApjzNFw9tWaNIF/Ub48lAt4nIL14ltMRsNoJbNclqGr8k6HwKKaUFLEDnH6iq5DqKaFKQGlsWrTmOXixihC6Jn//t0UxlpO6jiCZVOqDGxFdJFAT603pStQHXhM8DprqlaoTcC+YmRpoX0XiRSWIAzy8xTxHlczRiwRqlXOr/SP9BovL/4sGrTbORWpSF24xvcDQ5OXjfk7TabfXA6gMvs9CEbf5XP5JqsyCsKbLJRbeXX6zyU6wGCe7Epd36D96wMdUBLzEZc47aImxTea2z0teeuYrbnD+nLTwa1yXHbZE+UdE="
